### ISSUE TITLE
Can't create new citations in Firefox

### ISSUE THREAD

**Issue by NMyrholm** [MargaretKrutikova/re-cite#24]
Currently in Firefox (both desktop and mobile version), you can't save a citation to a collection. What happens is that when you enter the necessary details and press save, the window closes as normal but the collection doesn't receive the new citation.

Firefox Version: 73.0.1

**Comment by MargaretKrutikova** [comment]
Thanks a lot for reporting this issue! I will look into it over the weekend 😄

**Comment by MargaretKrutikova** [comment]
Btw, what OS were you using? I suppose it was windows?

**Comment by NMyrholm** [comment]
Both windows 10 (firefox 73.0.1) and Samsung 9 (firefox 68.5) :)

**Comment by MargaretKrutikova** [comment]
Fixed in the latest version! 😄
