### ISSUE TITLE
Feedback/success indicator when adding a citation

### ISSUE THREAD

**Issue by Yakimych** [MargaretKrutikova/re-cite#42]
It's not immediately obvious whether a citation has been successfully added, unless it immediately appears on the screen. This is, however, not the case for citations added for earlier dates.
Would be nice to have some sort of visual confirmation (toastr-like), that says e.g. "Citation added" as soon as the server returns a success status code.

**Comment by MargaretKrutikova** [comment]
Oh, yes, that's right, haven't thought about it. Thanks for reporting, I will look into it!
