### ISSUE TITLE
Pre-set date to "Today"

### ISSUE THREAD

**Issue by Yakimych** [MargaretKrutikova/re-cite#8]
Looks like the date is hardcoded to 2019-09-21. I can imagine that the citations are going to be added as-they-happen most of the time. Can we have todays date preselected?

**Comment by MargaretKrutikova** [comment]
Yes, that was the original plan, but something went wrong 😛 Fixing it!

**Comment by MargaretKrutikova** [comment]
It wasn't hardcoded to today's date actually, was just using `getMonth` from JS, which starts from zero, so it was the previous month 🤦‍♂ Thanks for submitting the issue!

**Comment by Yakimych** [comment]
Thanks for fixing it! 😄
